// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApdxeIMlrCJd8kDuvSE0lneK1ZFGJv4PE',
    appId: '1:801042934937:web:862c06f9b928e173f6dc08',
    messagingSenderId: '801042934937',
    projectId: 'e-commerce-firebase-6da6d',
    authDomain: 'e-commerce-firebase-6da6d.firebaseapp.com',
    storageBucket: 'e-commerce-firebase-6da6d.firebasestorage.app',
    measurementId: 'G-8T8YMFPRC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA66WkmjRANDjeNT_u4ANJ4_V6ew-9q-Wg',
    appId: '1:801042934937:android:b0754abae3af5779f6dc08',
    messagingSenderId: '801042934937',
    projectId: 'e-commerce-firebase-6da6d',
    storageBucket: 'e-commerce-firebase-6da6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5SjVHBt16BeR9Q4fN4aXFSnFUtCESdy4',
    appId: '1:801042934937:ios:69453e85e99f88d5f6dc08',
    messagingSenderId: '801042934937',
    projectId: 'e-commerce-firebase-6da6d',
    storageBucket: 'e-commerce-firebase-6da6d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5SjVHBt16BeR9Q4fN4aXFSnFUtCESdy4',
    appId: '1:801042934937:ios:69453e85e99f88d5f6dc08',
    messagingSenderId: '801042934937',
    projectId: 'e-commerce-firebase-6da6d',
    storageBucket: 'e-commerce-firebase-6da6d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApdxeIMlrCJd8kDuvSE0lneK1ZFGJv4PE',
    appId: '1:801042934937:web:27f5f0de7038667df6dc08',
    messagingSenderId: '801042934937',
    projectId: 'e-commerce-firebase-6da6d',
    authDomain: 'e-commerce-firebase-6da6d.firebaseapp.com',
    storageBucket: 'e-commerce-firebase-6da6d.firebasestorage.app',
    measurementId: 'G-X8Q46VQKPH',
  );
}
